### ISSUE TITLE
[BUG] Docs reflect old version

### ISSUE THREAD

**Issue by zgagnon** [frontegg/frontegg-nextjs#20]
**Describe the bug**
The documentation at https://docs.frontegg.com/docs/nextjs-1 reflects @frontegg/nextjs@4.0.17

**To Reproduce**

1. Visit https://docs.frontegg.com/docs/nextjs-1
1. Read the docs
 
**Expected behavior**

Documentation page uses the most recent version, or gives option to select it

**Screenshots**

<img width="861" alt="image" src="https://user-images.githubusercontent.com/324922/173104937-9c27b70c-8965-4c93-8192-c5dc63364e2e.png">

**Additional context**

**Comment by mcmxcdev** [comment]
I am really confused now what the correct way is to implement `@frontegg/nextjs`.
There two different ways outlined to set it up-

Also, I have `@frontegg/nextjs": "^4.0.20"` installed as latest but the tags and releases in this repository point to v5....

**Comment by rotemzif1** [comment]
@mcmxcdev we are working on the docs to make it suitable. thanks for the feedback. is there anything else here you are still experience?

**Comment by mcmxcdev** [comment]
All good for now, will report here if anything pops up.
