### ISSUE TITLE
[BUG] Project creator doesn't work

### ISSUE THREAD

**Issue by zgagnon** [frontegg/frontegg-nextjs#21]
**Describe the bug**
Running the create-next-app command fails  with 

``` 
Could not locate the repository for "https://github.com/frontegg/frontegg-nextjs/tree/main". Please check that the repository exists and try again.
```

**To Reproduce**

1. Open a terminal
2. Run project creator command `npx create-next-app --example "https://github.com/frontegg/frontegg-nextjs/tree/main" --example-path "apps/example" my-nextjs-app-name`

**Expected behavior**

A new next project with frontegg is created

**Screenshots**

**Additional context**

**Comment by rotemzif1** [comment]
@zgagnon now its fixed!

**Comment by rotemzif1** [comment]
https://github.com/frontegg/frontegg-nextjs/pull/42
כןסק
