### ISSUE TITLE
Implement a proper changelog according to semver

### ISSUE THREAD

**Issue by mcmxcdev** [frontegg/frontegg-nextjs#26]
**Describe the bug**
When upgrading versions, it is unclear what changed/improved and what could potentially break.

**Expected behavior**
It would be great to have descriptions of all the changes within a patch/minor/major release in tags/releases or a `CHANGELOG.md` file, same like in https://github.com/frontegg/frontegg-react/blob/master/CHANGELOG.md (which is outdated though)

**Comment by rotemzif1** [comment]
@mcmxcdev We are currently working on this. It should be public in the upcoming month. Thank you!

**Comment by rotemzif1** [comment]
Hey, check out our new changelog which we now fully support. Let me know if anything is still missing. Thanks! @mcmxcdev

**Comment by mcmxcdev** [comment]
Looks good to me, thanks!
