### ISSUE TITLE
[BUG] TS error when rendering `<FronteggAppProvider />`, missing `env...` props

### ISSUE THREAD

**Issue by chrishutchinson** [frontegg/frontegg-nextjs#302]
**Describe the bug**

The Next.js Frontegg [documentation here](https://docs.frontegg.com/docs/nextjs-12-13-ssr-hosted-login#nextjs-appdir-architecture) advises creating an `./app/layout.tsx` file to render `<FronteggAppProvider />` like so:

```tsx
{/* @ts-expect-error Server Component for more details visit: https://github.com/vercel/next.js/issues/42292 */}
<FronteggAppProvider authOptions={authOptions} hostedLoginBox={true}>
  {children}
</FronteggAppProvider>
```

Having done this, I believe the `@ts-expect-error` comment is masking an issue with the typings of the component, where it requires `envAppUrl`, `envBaseUrl`, and `envClientId` to be provided as props (though these are inferred from my `.env.local` file otherwise).

The TS error is as follows:

```
Type '{ children: ReactNode; authOptions: { keepSessionAlive: boolean; }; hostedLoginBox: true; }' is missing the following properties from type 'Omit<ClientFronteggProviderProps, "contextOptions">': envAppUrl, envBaseUrl, envClientId ts(2739)
```

I believe this could be two separate bugs:

1. The `@ts-expect-error` comment from your docs isn't actually required (at least not in the latest version of Next.js for me, where async server components are now supported)
2. The props type for `FronteggAppProvider` is slightly wrong or the usage documentation needs to be updated (either the `env...` props are optional, or the docs should cover passing them)

**To Reproduce**
Steps to reproduce the behaviour:

1. Follow the setup guide up to [this point](https://docs.frontegg.com/docs/nextjs-12-13-ssr-hosted-login#nextjs-appdir-architecture)
2. Remove the `@ts-expect-error` comment preceding the rendering of `<FronteggAppProvider />`

**Expected behaviour**
No TS error, or expect error comment

**Comment by yuvalotem1** [comment]
@chrishutchinson  Thank you for letting us know about this issue.
The types have been fixed since version `8.0.10`.
Therefore, I'm closing this issue.
