### ISSUE TITLE
[Request] Add support for Nextjs v15

### ISSUE THREAD

**Issue by KamalAman** [frontegg/frontegg-nextjs#371]
**Describe the bug**
Add support for https://nextjs.org/blog/next-15.  

**Expected behavior**
Frontegg Nextjs should be compatible with Nextjs v15

**Screenshots**
```
a cookie property was accessed directly with `cookies().getAll()`. `cookies()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
```

**Additional context**
See https://nextjs.org/docs/messages/sync-dynamic-apis

**Comment by MashaPav** [comment]
Hey @KamalAman thanks for bringing this to our attention!

Support for Next.js 15 was added in the latest version https://github.com/frontegg/frontegg-nextjs/releases/tag/v9.0.5.
