### ISSUE TITLE
[BUG] TS errors on `useAuth` usage with Typescript 4.8.2

### ISSUE THREAD

**Issue by mcmxcdev** [frontegg/frontegg-nextjs#52]
**Describe the bug**

I just attempted to upgrade from Typescript 4.7.4 to 4.8.2 and all code seemed to be fine except for usages of e.g. `const { user, isAuthenticated } = useAuth()`

The hook throws the following TS errors: 
```
Property 'user' does not exist on type '{}'.
Property 'isAuthenticated' does not exist on type '{}'.
```

When hovering over `useAuth` implementation, this is what Typescript 4.7.4 shows:

```
(alias) useAuth<{
    user: any;
    isAuthenticated: any;
}>(stateMapper?: AuthStateMapper<{
    user: any;
    isAuthenticated: any;
}> | undefined): {
    user: any;
    isAuthenticated: any;
}
```

With Typescript 4.8.2, it looks a bit different:

```
(alias) useAuth<object>(stateMapper?: AuthStateMapper<object> | undefined): object
```

The type definitions come from `@frontegg/react-hooks/auth/hooks.d.ts`

**Expected behavior**
No TS errors with Typescript 4.8.2

**Comment by rotemzif1** [comment]
@mcmxcdev this is fixed in our latest version. Let us know if you managed to get the fix. Thanks!

**Comment by mcmxcdev** [comment]
Works as expected now on our end, thank you!
