### ISSUE TITLE
[BUG] basePath setting not supported

### ISSUE THREAD

**Issue by adamcikado** [frontegg/frontegg-nextjs#70]
**Describe the bug**
SDK does not support Next.js `basePath` https://nextjs.org/docs/api-reference/next.config.js/basepath

**To Reproduce**
1. Add `basePath: 'test'` to `next.config.js`
2. Try to login
3. Redirect goes to wrong url, without basePath

**Expected behavior**
SDK should respect `basePath`

**Comment by yuvalotem1** [comment]
this should be fixed on latest version.
You can also provide `basename`  with relevant path as one of frontegg options.
