### ISSUE TITLE
[BUG] Success redirect from social login leads to 404

### ISSUE THREAD

**Issue by rost-rem** [frontegg/frontegg-nextjs#85]
**Describe the bug**

Trying to integrated Next.JS project with hosted login box. 
Using code from https://github.com/frontegg/frontegg-nextjs/tree/master/apps.
After Google sign - all good - redirected back to http://localhost:3000/account/social/success?state=fdssdf....
Then 404 error received.
Checked FronteggRouter.tsx - and only found login/logout routes (@frontegg/nextjs not handling this route).

**To Reproduce**

1. Use https://github.com/frontegg/frontegg-nextjs/tree/master/apps/example or follow Next.js integration docs.
2. Sign in with google.
3. Success. Redirect leads you back to localhost:3000 but nothing happens.

**Expected behavior**
Data from redirect processed to auth session.

![image](https://user-images.githubusercontent.com/115304397/196546631-9d93589f-eb8b-42b9-8c29-98311c8c394c.png)

**Comment by MashaPav** [comment]
Hey @rost-rem ! 

The frontegg/nextjs package is handling all the types of logins that we support and I couldn't reproduce the issue that you describe. Could you please provide your email address and we will continue investigating together over an email?

**Comment by rost-rem** [comment]
My mistake.
Social Login must be redirected to "[your-domain].frontegg.com/oauth" and not to localhost:3000
Everything is working now.

Thank you @MashaPav
