### ISSUE TITLE
[BUG] Edge runtime does not support 'crypto' module in when used in middleware

### ISSUE THREAD

**Issue by bguthrie** [frontegg/frontegg-nextjs#95]
**Describe the bug**
I'm trying to follow the README instructions to add the Frontegg middleware. When I paste that exact code into a `middleware.ts` and load my app in the Next dev server, I receive the following error:

`Error: The edge runtime does not support Node.js 'crypto' module.`

**To Reproduce**
1. Create a `middleware.ts`
2. Copy and paste the @frontegg/nextjs example
3. Open and load an endpoint in an app.

**Expected behavior**
I expected the middleware example to execute in the emulated NextJS runtime.

**Screenshots**
<img width="994" alt="image" src="https://user-images.githubusercontent.com/13945/201778487-8227287d-2ecd-41ac-801d-0db8beab86a7.png">

**Additional context**
@frontegg/nextjs 6.7.3
```
dependencies:
@frontegg/nextjs 6.7.3
└─┬ iron-session 6.3.1
  └── @peculiar/webcrypto 1.4.1
```

**Comment by bguthrie** [comment]
IronSession seems to indicate that a separate `import` is required: `https://github.com/vvo/iron-session/issues/543`

**Comment by yuvalotem1** [comment]
@bguthrie 
you can import getSession for edge runtime on the latest version like this
`import { getSession } from '@frontegg/nextjs/edge';
`
